// ═══════════════════════════════════════════════════════════════════
//  HERMES GLOBAL COUNTRY DATABASE — 195 Nations
//  Numeric ISO 3166-1 → {m: modern, a: ancient, c: color, e: estate}
// ═══════════════════════════════════════════════════════════════════
export const COUNTRY_DB = {
    "840": { m: "United States", a: "Turtle Island / Vinland Realms", c: 0x4169E1, e: "Continental Grid" },
    "124": { m: "Canada", a: "Hyperborean Tundra / Kanata", c: 0xDC143C, e: "Boreal Frontier" },
    "484": { m: "Mexico", a: "Anahuac / Aztec Alliance", c: 0x006644, e: "Pyramid Sector" },
    "320": { m: "Guatemala", a: "Mayapan / Quiche Kingdom", c: 0x20B2AA, e: "Jade Jungle" },
    "84": { m: "Belize", a: "Itza Domain", c: 0xFF4500, e: "Coastal Hub" },
    "222": { m: "El Salvador", a: "Cuscatlan Territory", c: 0x000080, e: "Volcanic Keep" },
    "340": { m: "Honduras", a: "Copan Dynastic Reach", c: 0x4682B4, e: "Valley Vault" },
    "558": { m: "Nicaragua", a: "Nicarao Chiefdoms", c: 0x5F9EA0, e: "Lakeside Ward" },
    "188": { m: "Costa Rica", a: "Talamanca Sanctuary", c: 0x008B8B, e: "Cloud Outpost" },
    "591": { m: "Panama", a: "Cueva Transit Nexus", c: 0xB22222, e: "Oceanic Gateway" },
    "192": { m: "Cuba", a: "Colba Taino Realm", c: 0x1E90FF, e: "Island Fortress" },
    "332": { m: "Haiti", a: "Ayiti Mountain Realm", c: 0x9400D3, e: "Crag Citadel" },
    "214": { m: "Dominican Republic", a: "Quisqueya Dominion", c: 0x00F5FF, e: "Coral Redoubt" },
    "388": { m: "Jamaica", a: "Xaymaca Timber Domain", c: 0x008000, e: "Springs Outpost" },
    "44": { m: "Bahamas", a: "Lucayan Archipelago", c: 0x00CED1, e: "Lagoon Vault" },
    "52": { m: "Barbados", a: "Ichirouganaim Outpost", c: 0xFFD700, e: "Reef Bastion" },
    "28": { m: "Antigua and Barbuda", a: "Wadadli Island Domain", c: 0x708090, e: "Shoreline Grid" },
    "212": { m: "Dominica", a: "Wai'tukubuli Mountain", c: 0x2E8B57, e: "Peak Redoubt" },
    "308": { m: "Grenada", a: "Camerhogne Spice Realm", c: 0xD2691E, e: "Spice Sanctuary" },
    "659": { m: "St Kitts and Nevis", a: "Liamuiga Fertile Fields", c: 0x00FF7F, e: "Volcano Base" },
    "662": { m: "St Lucia", a: "Hewanorra Realm", c: 0x87CEEB, e: "Spire Citadel" },
    "670": { m: "St Vincent and the Grenadines", a: "Hairoun Domain", c: 0xFF8C00, e: "Archipelago Hub" },
    "780": { m: "Trinidad and Tobago", a: "Iere Land of the Hummingbird", c: 0xCD5C5C, e: "Delta Outpost" },
    "76": { m: "Brazil", a: "Pindorama / Amazonia", c: 0x009739, e: "Rainforest Grid" },
    "32": { m: "Argentina", a: "Tierra de la Plata / Pampa", c: 0x74ACDF, e: "Estancia Plains" },
    "170": { m: "Colombia", a: "El Dorado / Chibcha Realm", c: 0xFCD116, e: "Andean Vault" },
    "604": { m: "Peru", a: "Tawantinsuyu / Inca Empire", c: 0xD91414, e: "Machu Spire" },
    "862": { m: "Venezuela", a: "Paria Open Waters", c: 0x00247D, e: "Orinoco Base" },
    "152": { m: "Chile", a: "Wallmapu / Mapuche Domain", c: 0x0039A6, e: "Pacific Trench" },
    "218": { m: "Ecuador", a: "Quitsa / Kingdom of Quito", c: 0xFFCC00, e: "Equatorial Apex" },
    "68": { m: "Bolivia", a: "Qullasuyu Highlands", c: 0x007A33, e: "Altiplano Mine" },
    "600": { m: "Paraguay", a: "Guarani Heartlands", c: 0xD52B1E, e: "Riverine Keep" },
    "858": { m: "Uruguay", a: "Banda Oriental Realms", c: 0x0081C6, e: "Estuary Sanctum" },
    "328": { m: "Guyana", a: "Guiana Land of Waters", c: 0x009E49, e: "Cataract Vault" },
    "740": { m: "Suriname", a: "Surinen Hinterlands", c: 0xFF0000, e: "Wilderness Grid" },
    "380": { m: "Italy", a: "Imperium Romanum", c: 0x800080, e: "Marble Senate" },
    "300": { m: "Greece", a: "Hellenic League / Hellas", c: 0x005A9C, e: "Acropolis Hold" },
    "250": { m: "France", a: "Gallia / Francia", c: 0x0055A4, e: "Chateau Grid" },
    "724": { m: "Spain", a: "Hispania / Iberia", c: 0xAA151B, e: "Alcazar Citadel" },
    "620": { m: "Portugal", a: "Lusitania Domain", c: 0x006600, e: "Maritime Keep" },
    "276": { m: "Germany", a: "Germania Magna / Holy Roman", c: 0xFFCC00, e: "Rhine Fortress" },
    "826": { m: "United Kingdom", a: "Britannia / Albion Realms", c: 0x00247D, e: "Baronial Keep" },
    "372": { m: "Ireland", a: "Eire / Gaelic Clans", c: 0x169B62, e: "Celtic Redoubt" },
    "528": { m: "Netherlands", a: "Belgica / Batavian Lowlands", c: 0x21468B, e: "Polder Complex" },
    "56": { m: "Belgium", a: "Gallia Belgica", c: 0xFFE32A, e: "Guildhall Grid" },
    "442": { m: "Luxembourg", a: "Lucilinburhuc Stronghold", c: 0x4169E1, e: "Countship Vault" },
    "756": { m: "Switzerland", a: "Confoederatio Helvetica", c: 0xD52B1E, e: "Alpine Bunker" },
    "40": { m: "Austria", a: "Ostarichi Eastern Realm", c: 0xED2939, e: "Danube Palace" },
    "616": { m: "Poland", a: "Lechia / Polish-Lithuanian", c: 0xDC143C, e: "White Eagle Hold" },
    "203": { m: "Czech Republic", a: "Bohemia / Great Moravia", c: 0x11457E, e: "Gothic Spire" },
    "703": { m: "Slovakia", a: "Nitra Principality", c: 0x0B4EA2, e: "Carpathian Hold" },
    "348": { m: "Hungary", a: "Pannonia / Lands of Arpad", c: 0x436F4D, e: "Citadel Buda" },
    "642": { m: "Romania", a: "Dacia / Wallachia Core", c: 0x002B7F, e: "Transylvanian Wall" },
    "100": { m: "Bulgaria", a: "Thracian / Bulgarian Empire", c: 0x00966E, e: "Tsarevets Hold" },
    "208": { m: "Denmark", a: "Daneland Viking Domain", c: 0xC8102E, e: "Fjord Bastion" },
    "752": { m: "Sweden", a: "Svear Kingdom / Svitjod", c: 0x006AA7, e: "Baltic Ward" },
    "578": { m: "Norway", a: "Norðvegr North Way", c: 0xEF2B2D, e: "Glacier Fortress" },
    "246": { m: "Finland", a: "Suomi Fennia Tribes", c: 0x003580, e: "Taiga Outpost" },
    "233": { m: "Estonia", a: "Aestii Baltic Domain", c: 0x0072CE, e: "Livonian Keep" },
    "428": { m: "Latvia", a: "Lettigallia / Livonia", c: 0x9E1B32, e: "River Fortress" },
    "440": { m: "Lithuania", a: "Grand Duchy of Lituania", c: 0xFDB913, e: "Gediminas Tower" },
    "804": { m: "Ukraine", a: "Kievan Rus / Kyivan Domain", c: 0xFFD700, e: "Steppe Redoubt" },
    "112": { m: "Belarus", a: "White Ruthenia Lands", c: 0xC8102E, e: "Woodland Vault" },
    "498": { m: "Moldova", a: "Moldavia Principality", c: 0x002B7F, e: "Vineyard Keep" },
    "643": { m: "Russia", a: "Tsardom of Muscovy / Novgorod", c: 0xDA291C, e: "Kremlin Base" },
    "191": { m: "Croatia", a: "Illyria / Dalmatia Realm", c: 0xFF0000, e: "Adriatic Wall" },
    "705": { m: "Slovenia", a: "Carantania Domain", c: 0x0038A8, e: "Karst Sanctuary" },
    "70": { m: "Bosnia and Herzegovina", a: "Illyrian Kingdom of Bosnia", c: 0x002395, e: "Dinaric Vault" },
    "688": { m: "Serbia", a: "Rascia / Serbian Empire", c: 0xC6363C, e: "White Fort" },
    "499": { m: "Montenegro", a: "Doclea / Zeta Principality", c: 0xD4AF37, e: "Black Crag Tower" },
    "8": { m: "Albania", a: "Illyrian Arberia", c: 0xFF0000, e: "Eagle Citadel" },
    "807": { m: "North Macedonia", a: "Paeonia / Ancient Macedon", c: 0xD20000, e: "Solar Redoubt" },
    "470": { m: "Malta", a: "Melite Knights Outpost", c: 0xEE2436, e: "Bastion Valetta" },
    "352": { m: "Iceland", a: "Thule Ocean Colony", c: 0x003897, e: "Basalt Vault" },
    "20": { m: "Andorra", a: "Marca Hispanica Fief", c: 0x0018A8, e: "Valleys Redoubt" },
    "492": { m: "Monaco", a: "Monoikos Rock", c: 0xE61C38, e: "Harbor Palace" },
    "674": { m: "San Marino", a: "Titanus Republic Base", c: 0x4A90E2, e: "Mountain Apex" },
    "336": { m: "Vatican City", a: "Mons Vaticanus District", c: 0xFFE600, e: "Sacred Sanctuary" },
    "356": { m: "India", a: "Bharatavarsha / Maurya Empire", c: 0xFF9933, e: "Saffron Palace" },
    "156": { m: "China", a: "Zhongguo / Dynastic Han-Tang", c: 0xDE2910, e: "Forbidden Spire" },
    "392": { m: "Japan", a: "Nippon / Yamato Shogunate", c: 0xBC002D, e: "Samurai Keep" },
    "410": { m: "South Korea", a: "Joseon / Goryeo Kingdom", c: 0x0047A0, e: "Hanok Sanctuary" },
    "408": { m: "North Korea", a: "Goguryeo Warlord Frontier", c: 0xC8102E, e: "Iron Bastion" },
    "496": { m: "Mongolia", a: "Khamag Mongol / Nomad Empire", c: 0x002E6E, e: "Steppe Pavilion" },
    "364": { m: "Iran", a: "Persia / Achaemenid Empire", c: 0x239F40, e: "Persepolis Vault" },
    "368": { m: "Iraq", a: "Mesopotamia / Babylon Core", c: 0x007A3D, e: "Ziggurat Grid" },
    "792": { m: "Turkey", a: "Anatolia / Hittite / Ottoman", c: 0xE30A17, e: "Sultanate Tower" },
    "760": { m: "Syria", a: "Aram-Damascus / Seleucid", c: 0xCE1126, e: "Oasis Citadel" },
    "422": { m: "Lebanon", a: "Phoenicia Maritime Domain", c: 0x00A86B, e: "Cedar Bastion" },
    "376": { m: "Israel", a: "Kingdom of Israel and Judah", c: 0x0038A8, e: "Judean Keep" },
    "400": { m: "Jordan", a: "Nabataea / Petra Outpost", c: 0x007A3D, e: "Canyon Vault" },
    "682": { m: "Saudi Arabia", a: "Arabia Deserta Dynasties", c: 0x006C35, e: "Desert Palace" },
    "887": { m: "Yemen", a: "Saba / Sheba Kingdom", c: 0xCE1126, e: "Adobe Fortress" },
    "512": { m: "Oman", a: "Magan / Muscat Empire", c: 0x008000, e: "Oasis Redoubt" },
    "784": { m: "UAE", a: "Trucial Coastal Outposts", c: 0x00732F, e: "Mirage Spire" },
    "634": { m: "Qatar", a: "Catara Desert Sectors", c: 0x8D1B3D, e: "Coastal Tower" },
    "48": { m: "Bahrain", a: "Dilmun Paradise Civilization", c: 0xDA291C, e: "Pearling Vault" },
    "414": { m: "Kuwait", a: "Kadhima Trade Vectors", c: 0x007A3D, e: "Gulf Redoubt" },
    "398": { m: "Kazakhstan", a: "Scythian Khaganate Tribes", c: 0x00AFCA, e: "Nomadic Steppe" },
    "860": { m: "Uzbekistan", a: "Sogdia / Transoxiana", c: 0x00BFFF, e: "Samarkand Wall" },
    "795": { m: "Turkmenistan", a: "Margiana / Parthian Reach", c: 0x228B22, e: "Oasis Bastion" },
    "762": { m: "Tajikistan", a: "Samanid Imperial Hub", c: 0xCC0000, e: "Pamir Sanctuary" },
    "417": { m: "Kyrgyzstan", a: "Khaganate of the Kirghiz", c: 0xE30A17, e: "Tian Shan Base" },
    "4": { m: "Afghanistan", a: "Bactria / Aryana Highlands", c: 0x000000, e: "Mountain Ward" },
    "586": { m: "Pakistan", a: "Indus Valley / Meluhha", c: 0x01411C, e: "Mohenjo Citadel" },
    "524": { m: "Nepal", a: "Kirata / Licchavi Realm", c: 0xDC143C, e: "Himalayan Apex" },
    "64": { m: "Bhutan", a: "Lhomon / Druk Yul Land", c: 0xFF6600, e: "Dzong Fortress" },
    "50": { m: "Bangladesh", a: "Vanga / Gangaridai Empire", c: 0x006A4E, e: "Monsoon Delta" },
    "144": { m: "Sri Lanka", a: "Tambapanni / Anuradhapura", c: 0x800000, e: "Sigiriya Spire" },
    "462": { m: "Maldives", a: "Dheeva Mahel Archipelago", c: 0x007E3A, e: "Atoll Vault" },
    "104": { m: "Myanmar", a: "Bagan / Pagan Empire", c: 0xFECB00, e: "Golden Pagoda" },
    "764": { m: "Thailand", a: "Ayutthaya / Siam Kingdom", c: 0xA51931, e: "Erawan Hold" },
    "116": { m: "Cambodia", a: "Kambuja / Angkor Empire", c: 0x032EA1, e: "Angkor Citadel" },
    "418": { m: "Laos", a: "Lan Xang Million Elephants", c: 0xCE1126, e: "Mekong Sanctuary" },
    "704": { m: "Vietnam", a: "Van Lang / Champa / Annam", c: 0xDA251D, e: "Citadel of Hue" },
    "458": { m: "Malaysia", a: "Srivijaya / Melaka Sultanate", c: 0x003399, e: "Rainforest Base" },
    "702": { m: "Singapore", a: "Temasek Sea Town", c: 0xED1B24, e: "Merlion Vault" },
    "360": { m: "Indonesia", a: "Majapahit / Nusantara Archipelago", c: 0xFF0000, e: "Volcanic Palace" },
    "608": { m: "Philippines", a: "Rajahnate of Maynila / Tondo", c: 0x0038A8, e: "Barangay Keep" },
    "96": { m: "Brunei", a: "Barunai Maritime Empire", c: 0xF7E017, e: "Water Palace" },
    "626": { m: "Timor-Leste", a: "Timor Sea Chiefdoms", c: 0xDC241F, e: "Coastal Hold" },
    "818": { m: "Egypt", a: "Kemet / Pharaonic New Kingdom", c: 0xC5A059, e: "Luxor Vault" },
    "710": { m: "South Africa", a: "Mapungubwe Gold Kingdoms", c: 0x007A4D, e: "Diamond Quarry" },
    "504": { m: "Morocco", a: "Mauretania / Maghreb Al-Aksa", c: 0xC1272D, e: "Kasbah Fortress" },
    "12": { m: "Algeria", a: "Numidia Berber Kingdoms", c: 0x006233, e: "Atlas Citadel" },
    "788": { m: "Tunisia", a: "Carthage Phoenician Empire", c: 0xE70013, e: "Punic Redoubt" },
    "434": { m: "Libya", a: "Cyrenaica / Garamantes", c: 0x239E46, e: "Sahara Vault" },
    "729": { m: "Sudan", a: "Nubia / Kingdom of Kush", c: 0x007229, e: "Meroe Pyramid" },
    "728": { m: "South Sudan", a: "Sudd Nilotic Settlements", c: 0x000000, e: "Swamp Outpost" },
    "231": { m: "Ethiopia", a: "Aksumite Empire / Abyssinia", c: 0x078930, e: "Lalibela Rock" },
    "232": { m: "Eritrea", a: "Adulis Red Sea Hub", c: 0xEB1C24, e: "Coastal Trench" },
    "262": { m: "Djibouti", a: "Punt Land Scribe Sectors", c: 0x69B3E3, e: "Strait Outpost" },
    "706": { m: "Somalia", a: "Macrobia / Ajuran Sultanate", c: 0x4189DD, e: "Port Base" },
    "404": { m: "Kenya", a: "Azania / Swahili Coast Hub", c: 0x000000, e: "Savannah Ward" },
    "834": { m: "Tanzania", a: "Kilwa Sultanate Core", c: 0x1EB53A, e: "Kilimanjaro Apex" },
    "800": { m: "Uganda", a: "Buganda Kingdom Hinterlands", c: 0x000000, e: "Crater Sanctum" },
    "646": { m: "Rwanda", a: "Kingdom of Rwanda Peaks", c: 0x00A1DE, e: "Hills Outpost" },
    "108": { m: "Burundi", a: "Urundi High Domains", c: 0x11B153, e: "Ridge Redoubt" },
    "180": { m: "DR Congo", a: "Kongo Empire Deep Forest", c: 0x007FFF, e: "River Mega-Mine" },
    "178": { m: "Congo Republic", a: "Loango Coast Kingdoms", c: 0xFBDE4A, e: "Canopy Vault" },
    "266": { m: "Gabon", a: "Ogooue Tribal Alliances", c: 0x009E60, e: "Equator Shield" },
    "226": { m: "Equatorial Guinea", a: "Mbini Territorial Sectors", c: 0x319400, e: "Islet Redoubt" },
    "120": { m: "Cameroon", a: "Sao Civilization Hubs", c: 0x436F4D, e: "Highland Keep" },
    "566": { m: "Nigeria", a: "Nok / Benin / Oyo Empire", c: 0x008751, e: "Bronze Citadel" },
    "288": { m: "Ghana", a: "Wagadou / Ashanti Gold Coast", c: 0xEF3340, e: "Ashanti Vault" },
    "384": { m: "Cote d'Ivoire", a: "Gyaaman / Sanwi Kingdom", c: 0xF77F00, e: "Lagoon Base" },
    "430": { m: "Liberia", a: "Grain Coast Settlements", c: 0xBF0A30, e: "Forest Border" },
    "694": { m: "Sierra Leone", a: "Sapes Coast Networks", c: 0x1EB53A, e: "Diamond Ridge" },
    "324": { m: "Guinea", a: "Mali Empire Western Core", c: 0xCE1126, e: "Bauxite Hold" },
    "624": { m: "Guinea-Bissau", a: "Kaabu Empire Frontiers", c: 0xCE1126, e: "Estuary Ward" },
    "686": { m: "Senegal", a: "Jolof Empire Heartlands", c: 0x00853F, e: "Atlantic Citadel" },
    "270": { m: "Gambia", a: "Gambia River Trade Grid", c: 0xFF0000, e: "River Basin" },
    "132": { m: "Cape Verde", a: "Ilhas Atlanticas Base", c: 0x0038A8, e: "Volcano Reef" },
    "478": { m: "Mauritania", a: "Chingues Oasis Outposts", c: 0x006233, e: "Dune Fortress" },
    "466": { m: "Mali", a: "Timbuktu / Mansa Musa Realm", c: 0x14B53A, e: "Mud-Brick Keep" },
    "562": { m: "Niger", a: "Songhai / Air Sultanate", c: 0xE05206, e: "Trans-Sahara Hub" },
    "148": { m: "Chad", a: "Kanem-Bornu Empire Sectors", c: 0x002664, e: "Lake Citadel" },
    "140": { m: "Central African Republic", a: "Anza Tribal Shield Networks", c: 0x002868, e: "Equatorial Base" },
    "24": { m: "Angola", a: "Ndongo / Matamba Kingdoms", c: 0xC8102E, e: "Highland Trench" },
    "516": { m: "Namibia", a: "Namaqua Desert / Damaraland", c: 0x003580, e: "Coastal Desert" },
    "72": { m: "Botswana", a: "Batswana Tribal Capitals", c: 0x6CACE4, e: "Kalahari Vault" },
    "716": { m: "Zimbabwe", a: "Great Zimbabwe Stone Empire", c: 0x006747, e: "Granite Monolith" },
    "894": { m: "Zambia", a: "Maravi Empire / Barotseland", c: 0x198A00, e: "Zambezi Vault" },
    "454": { m: "Malawi", a: "Maravi Lake Civilizations", c: 0x000000, e: "Lakeside Keep" },
    "508": { m: "Mozambique", a: "Monomotapa Sea Outposts", c: 0x007168, e: "Channel Watch" },
    "450": { m: "Madagascar", a: "Merina Kingdom Highlands", c: 0xED1C24, e: "Baobab Fortress" },
    "480": { m: "Mauritius", a: "Dina Arobi Star System", c: 0xEA1026, e: "Basalt Shield" },
    "690": { m: "Seychelles", a: "Granitic Island Matrices", c: 0x003F87, e: "Oceanic Spire" },
    "174": { m: "Comoros", a: "Al-Qamar Moon Sultanates", c: 0x3A75C4, e: "Islet Complex" },
    "426": { m: "Lesotho", a: "Basutoland Mountain Enclave", c: 0x00209F, e: "Sky Kingdom Tower" },
    "748": { m: "Eswatini", a: "Swazi Kingdom Sanctuaries", c: 0xB10C0C, e: "Royal Crag" },
    "678": { m: "Sao Tome and Principe", a: "Gulf of Guinea Outpost", c: 0x009E49, e: "Equator Tower" },
    "36": { m: "Australia", a: "Dreamtime Outback / Sahul", c: 0x00008B, e: "Red Rock Base" },
    "554": { m: "New Zealand", a: "Aotearoa / Maori Tribes", c: 0x00247D, e: "Glacial Spire" },
    "598": { m: "Papua New Guinea", a: "Tribal Highlands Matrix", c: 0xB22222, e: "Volcanic Vale" },
    "242": { m: "Fiji", a: "Viti Chiefdom Sovereignty", c: 0x68BFE3, e: "Reef Compound" },
    "90": { m: "Solomon Islands", a: "Melanesian Sea Frontiers", c: 0x0051BA, e: "Atoll Outpost" },
    "548": { m: "Vanuatu", a: "Kastom Island Alliances", c: 0xD21034, e: "Ash Spire" },
    "882": { m: "Samoa", a: "Sa-le-Faleupolu Core", c: 0x002B7F, e: "Pacific Base" },
    "776": { m: "Tonga", a: "Tu'i Tonga Maritime Empire", c: 0xC10020, e: "Ocean Palace" },
    "583": { m: "Micronesia", a: "Nan Madol Stone Networks", c: 0x0063A6, e: "Megalith Vault" },
    "584": { m: "Marshall Islands", a: "Ralik-Ratak Wave Charts", c: 0x0038A8, e: "Coral Chain" },
    "585": { m: "Palau", a: "Belau Core Archipelagos", c: 0x4A90E2, e: "Lagoon Base" },
    "296": { m: "Kiribati", a: "Tungaru Sea Domain", c: 0xD21034, e: "Ocean Horizon" },
    "798": { m: "Tuvalu", a: "Ellice Island Outposts", c: 0x4682B4, e: "Lowland Grid" },
    "520": { m: "Nauru", a: "Naoero Insular Domain", c: 0x00205B, e: "Phosphate Keep" }
};
